### PR TITLE
Improve collapse test, and reset view state after basic flow test

### LINKED ISSUE #42: testResignFirstResponderAndCollapse is not independent
The `testResignFirstResponderAndCollapse` test checks that the collapsed label shows "3 people", but does not add any tokens of its own: it assumes that `testBasicFlow` has run before it. As such, this test method cannot be run independently of the full suite.

### PR DESCRIPTION
**Pull request by brockboland**
Fixes #42

### CODE REVIEW

**Comment by ayanonagon** [comment]
This is great, thank you! :octocat: One question, wouldn’t the test fail if any of the tests runs before the first test?

**Comment by brockboland** [comment]
It shouldn't! I added back-spacing at the end of `testBasicFlow` to reset to the starting state, and confirmed that `testResignFirstResponderAndCollapse` works when run alone or as part of the full suite of tests.

**Comment by ayanonagon** [comment]
I guess `testResignFirstResponderAndCollapse` puts you in the `3 people` state, but doesn’t affect the other tests. :+1:

**Comment by brockboland** [comment]
Ooh, good point: `testResignFirstResponderAndCollapse` is NOT resetting things to the starting state. It seems like there should be an `afterEach` method to clean things up, but it's tough because there's not a good way to clear all the existing tokens through KIF without simulating a bunch of backspaces.

**Comment by ayanonagon** [comment]
Yeah, definitely a little tough. For now though, this is a huge improvement, so I’ll merge it in. Thanks again @brockboland! :octocat:

**Pull request merged**
